# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.TURF_FRONTEND_IP }}
        username: ubuntu
        key: ${{ secrets.TURF_FRONTEND_KEY }}
        source: "/build"
        target: "/var/www/rebounce_turf_build_1"
        
    - name: Message for success to Teams
      if: success()
      run: |
        curl -H 'Content-Type: application/json' -d '{"text":"FRONT-END SERVER : ${{github.actor}} made commit to master -- FRONT-END SERVER BUILD SUCCESSFULLY"}' https://outlook.office.com/webhook/133b7a6e-0e17-4de1-a95c-29e7e52230c9@cba5068b-6ede-41be-a53e-6bbfa0f2cf2f/IncomingWebhook/1dd63c9dcc2a43c7bf1fbfea4f52e324/0cc5c37b-bf43-4b59-8697-95d2287616cc
        
    - name: Message for success to Teams
      if: failure()
      run: |
        curl -H 'Content-Type: application/json' -d '{"text":"FRONT-END SERVER : ${{github.actor}} made commit to main -- FRONT-END SERVER BUILD FAILED"}' https://outlook.office.com/webhook/133b7a6e-0e17-4de1-a95c-29e7e52230c9@cba5068b-6ede-41be-a53e-6bbfa0f2cf2f/IncomingWebhook/1dd63c9dcc2a43c7bf1fbfea4f52e324/0cc5c37b-bf43-4b59-8697-95d2287616cc
        
